"""Added height, weight, age to Usernames

Revision ID: 40edac72ccca
Revises: b0bfe17f72d2
Create Date: 2025-05-03 13:40:42.293374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40edac72ccca'
down_revision = 'b0bfe17f72d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernames', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernames', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
