"""empty message

Revision ID: 748c32d44ba6
Revises: fef45a8ea893
Create Date: 2025-05-13 14:36:05.177976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748c32d44ba6'
down_revision = 'fef45a8ea893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('completion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
