"""initial migration, fixing an issue with a previous migration.

Revision ID: a66519860340
Revises: 
Create Date: 2025-05-04 21:16:40.559823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66519860340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usernames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_username', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['friend_username'], ['usernames.username'], name='fk_friends_username'),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], name='fk_friends_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'friend_username')
    )
    op.create_table('workout_history',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('weights', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], name='fk_workouts_user_id'),
    sa.PrimaryKeyConstraint('workout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_history')
    op.drop_table('friends')
    op.drop_table('usernames')
    # ### end Alembic commands ###
