"""Convert friends PK to composite (user_id, friend_username)

Revision ID: ad09dd8b27ab
Revises: cfd3f289f0d6
Create Date: 2025-05-03 16:37:49.378192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad09dd8b27ab'
down_revision = 'cfd3f289f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_username', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['friend_username'], ['usernames.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
