"""removes friends table to reinitialize it later

Revision ID: cfd3f289f0d6
Revises: ee89a1d87ee8
Create Date: 2025-05-03 16:35:05.085599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd3f289f0d6'
down_revision = 'ee89a1d87ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_username', sa.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['friend_username'], ['usernames.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
