"""Added a new friend table

Revision ID: ee89a1d87ee8
Revises: 40edac72ccca
Create Date: 2025-05-03 15:54:55.104926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee89a1d87ee8'
down_revision = '40edac72ccca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_username', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['friend_username'], ['usernames.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
