"""changed date time storage to non deprecated method

Revision ID: f8a030d91762
Revises: 748c32d44ba6
Create Date: 2025-05-15 23:36:43.203352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a030d91762'
down_revision = '748c32d44ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('completion')

    # ### end Alembic commands ###
