"""empty message

Revision ID: fef45a8ea893
Revises: 3c5fabd4d180
Create Date: 2025-05-13 14:15:27.777308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef45a8ea893'
down_revision = '3c5fabd4d180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['usernames.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['usernames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('friends')
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', sa.Boolean(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_history', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('completion')

    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_username', sa.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['friend_username'], ['usernames.username'], name='fk_friends_username'),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], name='fk_friends_user_id'),
    sa.PrimaryKeyConstraint('user_id', 'friend_username')
    )
    op.drop_table('friendships')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
